### ISSUE TITLE
Issue with make example

### ISSUE THREAD

**Issue by stevef1uk** [smallnest/gen#107]
Having run make tools; make build; make install I tried make example.
I am seeing an issue with:
github.com/gogo/protobuf/gogoproto/gogo.proto does not exist on path - install with
go get -u github.com/gogo/protobuf/proto

writing Makefile
writing main.proto
github.com/gogo/protobuf/gogoproto/gogo.proto does not exist on path - install with
go get -u github.com/gogo/protobuf/proto

Error compiling proto file github.com/gogo/protobuf/gogoproto/gogo.proto does not exist
Error in executing generate github.com/gogo/protobuf/gogoproto/gogo.proto does not exist
exit status 1

I had similar problems following the instructions for a quick start, before trying to build gen myself.

I noticed a couple more errors logged:
**Error calling func: github.com/smallnest/gen/dbmeta.LoadSqliteMeta error: unsupported table: sqlite_sequence**
LoadMeta Error getting table info for sqlite_sequence error: unsupported table: sqlite_sequence

Full log:
stevef@Stevens-MacBook-Pro-3 gen % gen --version
v0.9.16 (06/29/2020)
stevef@Stevens-MacBook-Pro-3 gen % make example
rm -rf ./example/Makefile \
	 ./example/README.md \
	 ./example/api \
	 ./example/app \
	 ./example/bin \
	 ./example/dao \
	 ./example/docs \
	 ./example/go.mod \
	 ./example/go.sum \
	 ./example/model \
	 ./example/.gitignore \
	 ./tests
ls -latr ./example
total 1736
drwxr-xr-x   3 stevef  staff      96 30 Jun 16:23 .
-rw-r--r--   1 stevef  staff  887808 30 Jun 16:23 sample.db
drwxr-xr-x  26 stevef  staff     832 30 Jun 16:25 ..
cd ./example && go run .. \
		--sqltype=sqlite3 \
		--connstr "./sample.db" \
		--database main \
		--module github.com/alexj212/generated \
		--verbose \
		--overwrite \
		--out ./ \
		--templateDir=../template \
		--json \
		--db \
		--generate-dao \
		--generate-proj \
		--protobuf \
		--gorm \
		--guregu \
		--rest \
		--mod \
		--server \
		--makefile \
		--copy-templates
   [0] [GEN_README.md.tmpl]
   [1] [Makefile.tmpl]
   [2] [README.md.tmpl]
   [3] [api.go.tmpl]
   [4] [api_add.go.tmpl]
   [5] [api_delete.go.tmpl]
   [6] [api_get.go.tmpl]
   [7] [api_getall.go.tmpl]
   [8] [api_update.go.tmpl]
   [9] [code_dao_gorm.md.tmpl]
   [10] [code_dao_sqlx.md.tmpl]
   [11] [code_http.md.tmpl]
   [12] [dao_gorm.go.tmpl]
   [13] [dao_gorm_add.go.tmpl]
   [14] [dao_gorm_delete.go.tmpl]
   [15] [dao_gorm_get.go.tmpl]
   [16] [dao_gorm_getall.go.tmpl]
   [17] [dao_gorm_init.go.tmpl]
   [18] [dao_gorm_update.go.tmpl]
   [19] [dao_sqlx.go.tmpl]
   [20] [dao_sqlx_add.go.tmpl]
   [21] [dao_sqlx_delete.go.tmpl]
   [22] [dao_sqlx_get.go.tmpl]
   [23] [dao_sqlx_getall.go.tmpl]
   [24] [dao_sqlx_init.go.tmpl]
   [25] [dao_sqlx_update.go.tmpl]
   [26] [debug.txt]
   [27] [gitignore.tmpl]
   [28] [gomod.tmpl]
   [29] [http_utils.go.tmpl]
   [30] [main_gorm.go.tmpl]
   [31] [main_sqlx.go.tmpl]
   [32] [mapping.json]
   [33] [model.go.tmpl]
   [34] [model_base.go.tmpl]
   [35] [protobuf.tmpl]
   [36] [protomain.go.tmpl]
   [37] [protoserver.go.tmpl]
   [38] [router.go.tmpl]
Loaded 58 mappings from: internal
    Mapping:[ 0] -> bit
    Mapping:[ 1] -> bool
    Mapping:[ 2] -> tinyint
    Mapping:[ 3] -> int
    Mapping:[ 4] -> smallint
    Mapping:[ 5] -> mediumint
    Mapping:[ 6] -> int4
    Mapping:[ 7] -> int2
    Mapping:[ 8] -> integer
    Mapping:[ 9] -> bigint
    Mapping:[10] -> int8
    Mapping:[11] -> char
    Mapping:[12] -> enum
    Mapping:[13] -> varchar
    Mapping:[14] -> nvarchar
    Mapping:[15] -> longtext
    Mapping:[16] -> mediumtext
    Mapping:[17] -> text
    Mapping:[18] -> tinytext
    Mapping:[19] -> varchar2
    Mapping:[20] -> inet
    Mapping:[21] -> json
    Mapping:[22] -> jsonb
    Mapping:[23] -> nchar
    Mapping:[24] -> date
    Mapping:[25] -> datetime2
    Mapping:[26] -> datetime
    Mapping:[27] -> time
    Mapping:[28] -> timestamp
    Mapping:[29] -> timestamptz
    Mapping:[30] -> smalldatetime
    Mapping:[31] -> decimal
    Mapping:[32] -> double
    Mapping:[33] -> money
    Mapping:[34] -> real
    Mapping:[35] -> float
    Mapping:[36] -> float8
    Mapping:[37] -> binary
    Mapping:[38] -> blob
    Mapping:[39] -> longblob
    Mapping:[40] -> mediumblob
    Mapping:[41] -> varbinary
    Mapping:[42] -> numeric
    Mapping:[43] -> bpchar
    Mapping:[44] -> tsvector
    Mapping:[45] -> _text
    Mapping:[46] -> bytea
    Mapping:[47] -> USER_DEFINED
    Mapping:[48] -> uuid
    Mapping:[49] -> 
    Mapping:[50] -> utinyint
    Mapping:[51] -> usmallint
    Mapping:[52] -> umediumint
    Mapping:[53] -> uint
    Mapping:[54] -> ubigint
    Mapping:[55] -> udecimal
    Mapping:[56] -> udouble
    Mapping:[57] -> ufloat
tableName: albums
    [ 0] AlbumId                                        integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] Title                                          nvarchar(160)        null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 160     default: []
    [ 2] ArtistId                                       integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
**Error calling func: github.com/smallnest/gen/dbmeta.LoadSqliteMeta error: unsupported table: sqlite_sequence**
LoadMeta Error getting table info for sqlite_sequence error: unsupported table: sqlite_sequence
tableName: artists
    [ 0] ArtistId                                       integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] Name                                           nvarchar(120)        null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 120     default: []
tableName: customers
    [ 0] CustomerId                                     integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] FirstName                                      nvarchar(40)         null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 2] LastName                                       nvarchar(20)         null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 20      default: []
    [ 3] Company                                        nvarchar(80)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 80      default: []
    [ 4] Address                                        nvarchar(70)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 70      default: []
    [ 5] City                                           nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 6] State                                          nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 7] Country                                        nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 8] PostalCode                                     nvarchar(10)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 10      default: []
    [ 9] Phone                                          nvarchar(24)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 24      default: []
    [10] Fax                                            nvarchar(24)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 24      default: []
    [11] Email                                          nvarchar(60)         null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 60      default: []
    [12] SupportRepId                                   integer              null: true   primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
tableName: employees
    [ 0] EmployeeId                                     integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] LastName                                       nvarchar(20)         null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 20      default: []
    [ 2] FirstName                                      nvarchar(20)         null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 20      default: []
    [ 3] Title                                          nvarchar(30)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 30      default: []
    [ 4] ReportsTo                                      integer              null: true   primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 5] BirthDate                                      datetime             null: true   primary: false  isArray: false  auto: false  col: datetime        len: -1      default: []
    [ 6] HireDate                                       datetime             null: true   primary: false  isArray: false  auto: false  col: datetime        len: -1      default: []
    [ 7] Address                                        nvarchar(70)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 70      default: []
    [ 8] City                                           nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 9] State                                          nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [10] Country                                        nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [11] PostalCode                                     nvarchar(10)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 10      default: []
    [12] Phone                                          nvarchar(24)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 24      default: []
    [13] Fax                                            nvarchar(24)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 24      default: []
    [14] Email                                          nvarchar(60)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 60      default: []
tableName: genres
    [ 0] GenreId                                        integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] Name                                           nvarchar(120)        null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 120     default: []
tableName: invoices
    [ 0] InvoiceId                                      integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] CustomerId                                     integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 2] InvoiceDate                                    datetime             null: false  primary: false  isArray: false  auto: false  col: datetime        len: -1      default: []
    [ 3] BillingAddress                                 nvarchar(70)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 70      default: []
    [ 4] BillingCity                                    nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 5] BillingState                                   nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 6] BillingCountry                                 nvarchar(40)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 40      default: []
    [ 7] BillingPostalCode                              nvarchar(10)         null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 10      default: []
    [ 8] Total                                          numeric              null: false  primary: false  isArray: false  auto: false  col: numeric         len: -1      default: []
tableName: invoice_items
    [ 0] InvoiceLineId                                  integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] InvoiceId                                      integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 2] TrackId                                        integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 3] UnitPrice                                      numeric              null: false  primary: false  isArray: false  auto: false  col: numeric         len: -1      default: []
    [ 4] Quantity                                       integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
tableName: media_types
    [ 0] MediaTypeId                                    integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] Name                                           nvarchar(120)        null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 120     default: []
tableName: playlists
    [ 0] PlaylistId                                     integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] Name                                           nvarchar(120)        null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 120     default: []
tableName: playlist_track
    [ 0] PlaylistId                                     integer              null: false  primary: true   isArray: false  auto: false  col: integer         len: -1      default: []
    [ 1] TrackId                                        integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
tableName: tracks
    [ 0] TrackId                                        integer              null: false  primary: true   isArray: false  auto: true   col: integer         len: -1      default: []
    [ 1] Name                                           nvarchar(200)        null: false  primary: false  isArray: false  auto: false  col: nvarchar        len: 200     default: []
    [ 2] AlbumId                                        integer              null: true   primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 3] MediaTypeId                                    integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 4] GenreId                                        integer              null: true   primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 5] Composer                                       nvarchar(220)        null: true   primary: false  isArray: false  auto: false  col: nvarchar        len: 220     default: []
    [ 6] Milliseconds                                   integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 7] Bytes                                          integer              null: true   primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 8] UnitPrice                                      numeric              null: false  primary: false  isArray: false  auto: false  col: numeric         len: -1      default: []
Error calling func: github.com/smallnest/gen/dbmeta.LoadSqliteMeta error: unsupported table: sqlite_stat1
LoadMeta Error getting table info for sqlite_stat1 error: unsupported table: sqlite_stat1
tableName: purchase_order
    [ 0] id                                             integer              null: false  primary: true   isArray: false  auto: false  col: integer         len: -1      default: []
    [ 1] payment_id                                     integer              null: false  primary: false  isArray: false  auto: false  col: integer         len: -1      default: []
    [ 2] full_name                                      text                 null: false  primary: false  isArray: false  auto: false  col: text            len: -1      default: []
Generating code for the following tables (12)
[0] customers
[1] invoice_items
[2] media_types
[3] invoices
[4] playlists
[5] playlist_track
[6] tracks
[7] albums
[8] artists
[9] employees
[10] genres
[11] purchase_order
writing model/customers.go
writing api/customers.go
writing dao/customers.go
writing model/invoice_items.go
writing api/invoice_items.go
writing dao/invoice_items.go
writing model/media_types.go
writing api/media_types.go
writing dao/media_types.go
writing model/playlist_track.go
writing api/playlist_track.go
writing dao/playlist_track.go
writing model/tracks.go
writing api/tracks.go
writing dao/tracks.go
writing model/albums.go
writing api/albums.go
writing dao/albums.go
writing model/artists.go
writing api/artists.go
writing dao/artists.go
writing model/employees.go
writing api/employees.go
writing dao/employees.go
writing model/genres.go
writing api/genres.go
writing dao/genres.go
writing model/invoices.go
writing api/invoices.go
writing dao/invoices.go
writing model/playlists.go
writing api/playlists.go
writing dao/playlists.go
writing model/purchase_order.go
writing api/purchase_order.go
writing dao/purchase_order.go
writing api/router.go
writing api/http_utils.go
writing dao/dao_base.go
writing model/model_base.go
writing go.mod
github.com/gogo/protobuf/gogoproto/gogo.proto does not exist on path - install with
go get -u github.com/gogo/protobuf/proto

writing Makefile
writing main.proto
github.com/gogo/protobuf/gogoproto/gogo.proto does not exist on path - install with
go get -u github.com/gogo/protobuf/proto

Error compiling proto file github.com/gogo/protobuf/gogoproto/gogo.proto does not exist
Error in executing generate github.com/gogo/protobuf/gogoproto/gogo.proto does not exist
exit status 1
make: *** [generate_example] Error 1
stevef@Stevens-MacBook-Pro-3 gen %

**Comment by stevef1uk** [comment]
Ok, I looked into the code and can see that the problem is that my GOPATH is not set to my home directory, which is what the code expects. I created a symbolic link to make that assumption true and now I have a new problem:
# example.com/rest/example/app/server
app/server/main.go:106:2: undefined: daos
Error: exit status 2
Usage:
  packr2 build [flags]

**Comment by alexj212** [comment]
Should be resolved in  v0.9.17 (06/30/2020)

**Comment by stevef1uk** [comment]
Thanks that worked. I need need to build protoc for my mac though, which wasn't obvious. Anyone finding this in the future should start here: https://jwangee.github.io/blog/2017/12/08/protobuf1.html

**Comment by dwgeneral** [comment]
> Ok, I looked into the code and can see that the problem is that my GOPATH is not set to be my home directory, which is what the code expects in main.go. I created a symbolic link to make that assumption true and now I have a new problem:
> 
> # example.com/rest/example/app/server
> app/server/main.go:106:2: undefined: daos
> Error: exit status 2
> Usage:
> packr2 build [flags]
> 
> So, I made a couple of hacks to main.go to get the code to build bin/example and it runs. The bad news is that no data is being returned, which I find odd?

how do u fix it? I have the same issue "github.com/gogo/protobuf/gogoproto/gogo.proto does not exist", and my gopath is correct in my opinion.

**Comment by dwgeneral** [comment]
> > Ok, I looked into the code and can see that the problem is that my GOPATH is not set to be my home directory, which is what the code expects in main.go. I created a symbolic link to make that assumption true and now I have a new problem:
> > # example.com/rest/example/app/server
> > app/server/main.go:106:2: undefined: daos
> > Error: exit status 2
> > Usage:
> > packr2 build [flags]
> > So, I made a couple of hacks to main.go to get the code to build bin/example and it runs. The bad news is that no data is being returned, which I find odd?
> 
> how do u fix it? I have the same issue "github.com/gogo/protobuf/gogoproto/gogo.proto does not exist", and my gopath is correct in my opinion.

I fixed. change the path to suitable with it.
