### ISSUE TITLE
issue about postgresql with sample.sql file

### ISSUE THREAD

**Issue by dwgeneral** [smallnest/gen#122]
I wanna generate example by postgresql db and data from sample.sql file, when I add the file params on connStr
```
go run .. \
		--sqltype=postgres \
		--connstr "host=0.0.0.0 port=5432 user=gogogo dbname=gogogo password=123456 sslmode=disable file=sample.sql" \
		--database gogogo \
		--module github.com/alexj212/generated \
		--verbose \
		--overwrite \
		--out ./ \
		--templateDir=../template \
		--mapping=../template/mapping.json \
		--json \
		--db \
```

 I got this error
```
Error pinging database: pq: unrecognized configuration parameter "file"

Error in initializing db pq: unrecognized configuration parameter "file"
exit status 1
make: *** [generate_example] Error 1
```

so, what is the format with data source file, such as sample.sql like that ?

**Comment by alexj212** [comment]
You are using an incorrect format for the db connection string - 

Here is an example 

"host=127.0.0.1 port=5432 user=postgres dbname=dvdrental password=changeme sslmode=disable"

**Comment by dwgeneral** [comment]
> You are using an incorrect format for the db connection string -
> 
> Here is an example
> 
> "host=127.0.0.1 port=5432 user=postgres dbname=dvdrental password=changeme sslmode=disable"

I know it.  I wanna config the data source file (sample.sql) for Postgresql to replace with sample.db for SQLite . what is the correct format ?

**Comment by alexj212** [comment]
Here is an example of options - You would want to populate sqltype, connstr and  database options

```
        --sqltype=sqlite3 \
        --connstr "./sample.db" \
        --database main \
        --module github.com/alexj212/generated \
        --verbose \
        --overwrite \
        --out ./ \
        --json \
        --db \
        --api=apis \
        --dao=daos \
        --model=models \
        --generate-dao \
        --generate-proj \
        --protobuf \
        --gorm \
        --guregu \
        --rest \
        --mod \
        --server \
        --makefile \
        --run-gofmt \
```
