### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by ke00ke** [smallnest/gen#125]
**what did i do **
i just run command: `gen --sqltype=mysql --connstr "root:root@tcp(47.105.130.241:3306)/uniin_bi?charset=utf8" --database uniin_bi --json --gorm --guregu --rest --out ./example --module example.com/rest/example --mod --server --makefile --json-fmt=snake --generate-dao --generate-proj --overwrite`, 

**what happened**
it comes error logs: `panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/smallnest/gen/dbmeta.LoadMysqlMeta(0xc000
4bc780, 0xc00001a0ea, 0x5, 0xc00001a160, 0x4, 0xc000
51c120, 0x16, 0xa87900, 0xc0000d0000, 0x0, ...)
        D:/ckh/GOPATH/pkg/mod/github.com/smallnest/g
en@v0.9.23/dbmeta/meta_mysql.go:65 +0xce9
github.com/smallnest/gen/dbmeta.LoadMeta(0xc00001a0e
a, 0x5, 0xc0004bc780, 0xc00001a160, 0x4, 0xc00051c12
0, 0x16, 0x0, 0x0, 0x0, ...)
        D:/ckh/GOPATH/pkg/mod/github.com/smallnest/g
en@v0.9.23/dbmeta/meta.go:316 +0xc4
github.com/smallnest/gen/dbmeta.LoadTableInfo(0xc000
4bc780, 0xc000176000, 0x29, 0x40, 0x0, 0x0, 0x0, 0xc
000178000, 0x22)
        D:/ckh/GOPATH/pkg/mod/github.com/smallnest/g
en@v0.9.23/dbmeta/meta.go:694 +0x1bd
main.main()
        D:/ckh/GOPATH/pkg/mod/github.com/smallnest/g
en@v0.9.23/main.go:258 +0x7b1
`  
**but but i change the 'uniin_bi' database to another, it works! So, i got no way to handle this..**

**Comment by ke00ke** [comment]
**by the way , i also found root path stange auto add one diretory name 'exampl' , but i total name is 'example'**

**Comment by alexj212** [comment]
Try with the latest v0.9.24
