### ISSUE TITLE
when generate dao function. does not support composite primary key

### ISSUE THREAD

**Issue by ammend** [smallnest/gen#127]
model is as list
```
DROP TABLE IF EXISTS `abcd_apt`;
CREATE TABLE `abcd_apt` (
  `id` bigint(40) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `version` varchar(100) NOT NULL,
  `owner` varchar(100) NOT NULL,
  `desc` varchar(500) NOT NULL,
  PRIMARY KEY (`name`,`version`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
gorm is listed as below
// AbcdApt struct is a row record of the abcd_apt table in the bytesib database
type AbcdApt struct {
    //[ 0] id                                             bigint               null: false  primary: false  isArray: false  auto: true   col: bigint          len: -1      default: []
    ID int64 `gorm:"AUTO_INCREMENT;column:id;type:bigint;"`
    //[ 1] name                                           varchar(100)         null: false  primary: true   isArray: false  auto: false  col: varchar         len: 100     default: []
    Name string `gorm:"primary_key;column:name;type:varchar;size:100;"`
    //[ 2] version                                        varchar(100)         null: false  primary: false  isArray: false  auto: false  col: varchar         len: 100     default: []
    Version string `gorm:"column:version;type:varchar;size:100;"`
    //[ 3] owner                                          varchar(100)         null: false  primary: false  isArray: false  auto: false  col: varchar         len: 100     default: []
    Owner string `gorm:"column:owner;type:varchar;size:100;"`
    //[ 4] desc                                           varchar(500)         null: false  primary: false  isArray: false  auto: false  col: varchar         len: 500     default: []
    Desc string `gorm:"column:desc;type:varchar;size:500;"`
}

**Comment by ammend** [comment]
> model is as list
> 
> ```
> DROP TABLE IF EXISTS `abcd_apt`;
> CREATE TABLE `abcd_apt` (
>   `id` bigint(40) NOT NULL AUTO_INCREMENT,
>   `name` varchar(100) NOT NULL,
>   `version` varchar(100) NOT NULL,
>   `owner` varchar(100) NOT NULL,
>   `desc` varchar(500) NOT NULL,
>   PRIMARY KEY (`name`,`version`),
>   UNIQUE KEY `id` (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> ```
> 
> gorm is listed as below
> // AbcdApt struct is a row record of the abcd_apt table in the bytesib database
> type AbcdApt struct {
> //[ 0] id bigint null: false primary: false isArray: false auto: true col: bigint len: -1 default: []
> ID int64 `gorm:"AUTO_INCREMENT;column:id;type:bigint;"`
> //[ 1] name varchar(100) null: false primary: true isArray: false auto: false col: varchar len: 100 default: []
> Name string `gorm:"primary_key;column:name;type:varchar;size:100;"`
> //[ 2] version varchar(100) null: false primary: false isArray: false auto: false col: varchar len: 100 default: []
> Version string `gorm:"column:version;type:varchar;size:100;"`
> //[ 3] owner varchar(100) null: false primary: false isArray: false auto: false col: varchar len: 100 default: []
> Owner string `gorm:"column:owner;type:varchar;size:100;"`
> //[ 4] desc varchar(500) null: false primary: false isArray: false auto: false col: varchar len: 500 default: []
> Desc string `gorm:"column:desc;type:varchar;size:500;"`
> }

@alexj212 please help.

**Comment by ammend** [comment]
maybe I have found what's wrong. in dbmeta/meta_mysql
func mysqlParseDDL(ddl string) (colsDDL map[string]string, primaryKey string) 
primaryKey is set Only one key.

**Comment by ammend** [comment]
> maybe I have found what's wrong. in dbmeta/meta_mysql
> func mysqlParseDDL(ddl string) (colsDDL map[string]string, primaryKey string)
> primaryKey is set Only one key.

May I join u to fix this problem? @alexj212 @smallnest

**Comment by alexj212** [comment]
@ammend sure - composite keys are tricky cause it affects queries, api calls etc. Any code suggestions/ PR are welcome.

**Comment by ammend** [comment]
> @ammend sure - composite keys are tricky cause it affects queries, api calls etc. Any code suggestions/ PR are welcome.

pr is as listed below.
https://github.com/smallnest/gen/pull/128
