### ISSUE TITLE
[讨论]tinyint 是映射成 bool 好还是 int32 好？

### ISSUE THREAD

**Issue by leopku** [smallnest/gen#132]
目前 mapping.json 中是映射成 int32

 tinyint 映射成 bool 是不是更方便？而且更符合多数项目及其它语言的习惯。

**Comment by smallnest** [comment]
tinyint [0,255]
bool [true,false]

**Comment by leopku** [comment]
遗漏了 tinyint(1) ，不过刚查了一下括号里的 size 几乎不起什么实际作用。

实践中，个人遇到的项目中 tinyint(1) 几乎都映射为 bool

**Comment by leopku** [comment]
想了一下，代码里特殊处理吧。
Thanks.
