### ISSUE TITLE
undefined schema when using go get to install the lib

### ISSUE THREAD

**Issue by william-lg** [smallnest/gen#155]
~ % go get -u github.com/smallnest/gen  
# github.com/smallnest/gen/dbmeta
go/src/github.com/smallnest/gen/dbmeta/meta_mssql.go:19:15: undefined: schema.Table
go/src/github.com/smallnest/gen/dbmeta/meta_mysql.go:20:15: undefined: schema.Table
go/src/github.com/smallnest/gen/dbmeta/meta_postgres.go:18:15: undefined: schema.Table
go/src/github.com/smallnest/gen/dbmeta/meta_sqlite.go:38:15: undefined: schema.Table
go/src/github.com/smallnest/gen/dbmeta/meta_unknown.go:21:15: undefined: schema.Table

**Comment by william-lg** [comment]
go version: 1.16
GO111MODULE="auto"

**Comment by danysz** [comment]
go version go1.16.2 darwin/amd64
same error

**Comment by smallnest** [comment]
will update schema lib

**Comment by smallnest** [comment]
upgraded schema

**Comment by danysz** [comment]
How can I use the latest version ? When are you going to release a new version ?

**Comment by smallnest** [comment]
v0.9.28 released
