### ISSUE TITLE
Use sql.NullInt32 for INT4 

### ISSUE THREAD

**Issue by krhubert** [smallnest/gen#163]
Hi,

I would like to keep a more consistent types between database type and go struct, therefore it would be great to use `sq.NullInt32` for db `INT4` 
```go
type S struct {
    //[ 0] id INT4                 null: true   primary:     false  isArray: false  auto: false  col: INT4            len: -1      default: []
    ID sql.NullInt64 `gorm:"column:user_id;type:INT4;"`
}
```

**Comment by smallnest** [comment]
updated.

And will use sql.NullInt16 for INT2 if go 1.17 is released
