### ISSUE TITLE
Can't connect to mssql; don't find information how to use this tool

### ISSUE THREAD

**Issue by hbroer** [smallnest/gen#17]
Hi,

i tried to get structs of an existing mssql database, but it fails with an error

```
gen --sqltype "sqlserver" --connstr "server=localhost;user id=sa;password={xxx}" --database xxx  --json --gorm
```
=> `2019/05/24 14:09:39 unknown db driver *mssql.Driver`

same with
```
gen --sqltype "mssql" --connstr "server=localhost;user id=sa;password={xxx}" --database xxx  --json --gorm
```

different with "asdasd" instead of "mssql". Is this a bug, or do i use it wrong?

**Comment by smallnest** [comment]
This is an issue of  the jimsmart/schema.

See https://github.com/jimsmart/schema/blob/master/dialect.go#L32.

It should be `"*mssql.Driver":          &mssql,  `

You can  change it mannually or submit an issue to jimsmart/schema.

**Comment by jimsmart** [comment]
This is now fixed upstream in jimsmart/schema. Thanks.
