### ISSUE TITLE
doesn't generate model properties

### ISSUE THREAD

**Issue by alex347** [smallnest/gen#19]
All generated models have no properties generated
```
$ go version
go version go1.12.7 darwin/amd64
```

```
gen --connstr "root:root@tcp(127.0.0.1:3306)/abc?&parseTime=True" --database abc  --json --gorm --guregu --rest
```

```go
package model

import (
        "database/sql"
        "time"
        "github.com/guregu/null"
)

var (
        _ = time.Second
        _ = sql.LevelDefault
        _ = null.Bool{}
)

type Transaction struct {
}

// TableName sets the insert table name for this struct type
func (t *Transaction) TableName() string {
        return "transaction"
}
```

**Comment by smallnest** [comment]
check whether your table `Transaction` has contains some fields.

I have test with employees database . It can generate those structs:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/865763/62211763-f024ef80-b3d1-11e9-8cd0-85b7fb52d233.png">

**Comment by smallnest** [comment]
you can add some logs before https://github.com/smallnest/gen/blob/master/dbmeta/meta.go#L90

to check what columns have been fetched.

**Comment by alex347** [comment]
c.DatabaseTypeName() in [https://github.com/smallnest/gen/blob/master/dbmeta/meta.go#L115](https://github.com/smallnest/gen/blob/master/dbmeta/meta.go#L115)
returns an empty string.

From docs:
"If an empty string is returned the driver type name is not supported"
[https://golang.org/pkg/database/sql/#ColumnType.DatabaseTypeName](https://golang.org/pkg/database/sql/#ColumnType.DatabaseTypeName)
so it's something wrong with the mysql driver

**Comment by smallnest** [comment]
Maybe you should update dependency libs or check where it can access your database by your connection string, or mysql version issues? 


I have create the model by using your table:
```go
package model

import (
	"database/sql"
	"time"

	"github.com/guregu/null"
)

var (
	_ = time.Second
	_ = sql.LevelDefault
	_ = null.Bool{}
)

type Example struct {
	ID int         `gorm:"column:id;primary_key" json:"id"`
	C1 null.String `gorm:"column:c1" json:"c1"`
	C2 null.String `gorm:"column:c2" json:"c2"`
	C3 null.Int    `gorm:"column:c3" json:"c3"`
	C4 null.Time   `gorm:"column:c4" json:"c4"`
	C5 null.String `gorm:"column:c5" json:"c5"`
}

// TableName sets the insert table name for this struct type
func (e *Example) TableName() string {
	return "example"
}
```

**Comment by alex347** [comment]
updating dependencies solved it:
`go get -u `

**Comment by gipsh** [comment]
same problem here, i was using go 1.10 + mysql 7. 
updated to go 1.12 and worked.
