### ISSUE TITLE
If table name is order will case gen fail

### ISSUE THREAD

**Issue by iKuiki** [smallnest/gen#22]
if table name is 'order', the struct generated wiill be empty:

``` golang
package model

import (
	"database/sql"
	"time"

	"github.com/guregu/null"
)

var (
	_ = time.Second
	_ = sql.LevelDefault
	_ = null.Bool{}
)

type Order struct {
}

// TableName sets the insert table name for this struct type
func (o *Order) TableName() string {
	return "order"
}
```

gen param is```gen --connstr 'xxxx' --table order --gorm --json```

when I change table to order2, bug not show again

**Comment by smallnest** [comment]
fixed. support "order","like" sql keywords as table names

**Comment by leopku** [comment]
This issue appears again.

I have a table named `order`.

It throws `Error getting table info for order error: unable to load ddl from mysql: unable to load ddl from mysql: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order' at line 1
Generating code for the following tables (33)`.

Other tables worked fine.

**Comment by smallnest** [comment]
pull latest gen and test.

**Comment by alexj212** [comment]
This has been updated in v0.99 - table named order in mysql tested

**Comment by leopku** [comment]
@alexj212 v0.9.9 works fine.
