### ISSUE TITLE
Error in fetching tables information from mysql information schema

### ISSUE THREAD

**Issue by niaiwomattt** [smallnest/gen#25]
>gen --connstr "dev/123@tcp(192.168.1.242:3306)/gyys_user_center?charset=utf8mb4&parseTime=True&loc=Local" --database doctor_auth  --json --gorm --guregu --rest

MySQL 8.0

**Comment by smallnest** [comment]
what's the error?

**Comment by smallnest** [comment]
mysql8 uses new Authentication so you can't connect mysql. You can follow the below issue to use legacy Authentication.


https://github.com/go-sql-driver/mysql/issues/785
