### ISSUE TITLE
why the struct don't have member?

### ISSUE THREAD

**Issue by liaosimin** [smallnest/gen#26]
gen -c 'mitra:shopee123!@tcp(10.12.77.233)/apc_report_db?&parseTime=True' --database apc_report_db -t dp_order_report_tab --package dbreport --json --gorm --guregu

package model

import (
	"database/sql"
	"time"

	"github.com/guregu/null"
)

var (
	_ = time.Second
	_ = sql.LevelDefault
	_ = null.Bool{}
)

type DpOrderReportTab struct {
}

// TableName sets the insert table name for this struct type
func (d *DpOrderReportTab) TableName() string {
	return "dp_order_report_tab"
}

**Comment by smallnest** [comment]
maybe it is mysql 8.0 problem, see  #25 .

If you can use this mysql dsn string to login your  mysql, gen should succeed to generate those code.

If it is not  mysql 8.0 problem, maybe your table has some special defination, you can paste the table  here

**Comment by smallnest** [comment]
see #25

**Comment by smallnest** [comment]
also #19
