### ISSUE TITLE
mysql cann't generate go model struct 

### ISSUE THREAD

**Issue by noclear** [smallnest/gen#28]
in dbmeta/meta.go GenerateStruct function line101, when the tablename is user , the sql  string is  SELECT * FROM ```user ``` LIMIT 0  .  that is a error sql query string.

**Comment by smallnest** [comment]
need err details about the error

**Comment by noclear** [comment]
> need err details about the error

when i add fmt.Println("q=",q) fmt.Println("err=",err) in  github.com/jimsmart/schema/schema.go file on line 177.

the print is :  
q= SELECT * FROM ```user``` LIMIT 0
err=  Error 1146: Table 'test.`user`' doesn't exist

that is because add extra `` on tableName in the code :
-----------------------
cols, _ := schema.Table(db, fmt.Sprintf(tableNameFormat[sqlType], tableName))
-----------------------

**Comment by smallnest** [comment]
你的comment没格式化，看不清你具体问题，貌似你说的问题是因为```SELECT * FROM `user` LIMIT 0```中表的名称前后被加上了上撇号？

事实上这是mysql支持的，因为有些表明是sql关键字，直接写会有问题，比如`like`、`where`等

<img width="369" alt="image" src="https://user-images.githubusercontent.com/865763/70980546-74141580-20ee-11ea-99f6-7dcbac28ed78.png">

**Comment by noclear** [comment]
![Uploading 企业微信截图_15767476877076.png…]() 就是说 有三个 `` 了

**Comment by noclear** [comment]
![2](https://user-images.githubusercontent.com/6859090/71461012-3186c300-27e9-11ea-8c91-6241ff663c64.png)
导致的问题跟 https://github.com/smallnest/gen/issues/30 一样的.

**Comment by smallnest** [comment]
https://github.com/smallnest/gen/pull/23 引入的escape tablename,为了解决特殊表名的问题，之后  [jimsmart/schema](https://github.com/jimsmart/schema/issues/10) 也加入了这个修复，所以会导致重复 escape的问题。 

我reverted #23,   `go get -u -v github.com/smallnest/gen` 更新一下gen再测试一下,应该可以了
