### ISSUE TITLE
generated struct has no fields

### ISSUE THREAD

**Issue by 2030405043** [smallnest/gen#30]
`package model

import (
	"database/sql"
	"time"
	"github.com/guregu/null"
)

var (
	_ = time.Second
	_ = sql.LevelDefault
	_ = null.Bool{}
)

type UserAliinfo struct {
}

// TableName sets the insert table name for this struct type
func (u *UserAliinfo) TableName() string {
	return "user_aliinfo"
}
`

**Comment by smallnest** [comment]
see #25 : mysql 8 issue
see #19 : update golang and deps

**Comment by 2030405043** [comment]
mysql 5.7
golang:1.13 windows

**Comment by gatspy** [comment]
Have the same problem.

```
mysql: 5.7
go: 1.13 mac osx
```

**Comment by smallnest** [comment]
`go get -u -v github.com/jimsmart/schema` 试试，应该是这个库没有读取出表的 schema

**Comment by MaxJohnXiang** [comment]
I has the same problem , 
mysql: 5.7
go: 1.13 mac osx

---mysql version info
innodb_version	5.7.21
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1,TLSv1.2
version	5.7.21
version_comment	Homebrew
version_compile_machine	x86_64
version_compile_os	osx10.13


1. Already update go dep 
2. Already install schema

**Comment by smallnest** [comment]
最好把你的表信息贴上来以便debug,或者你自己看看schema为什么没能获取出数据库的元数据

**Comment by smallnest** [comment]
see #28, 看看是否是同一个问题，更新一下gen试试

**Comment by alexj212** [comment]
Can you provide the table ddl from a db dump?
