### ISSUE TITLE
Is it any way to generate json tag using Camel case?

### ISSUE THREAD

**Issue by hotdog132** [smallnest/gen#39]
As title. Is it any way to generate json tag using camel case? Thanks!

**Comment by smallnest** [comment]
you should change https://github.com/smallnest/gen/blob/master/dbmeta/meta.go#L125 to camelcase the key

**Comment by alexj212** [comment]
With the latest release you can use the following option

--json-fmt=

json name format [snake | camel | lower_camel | none
