### ISSUE TITLE
model_base.go.tmpl not found error

### ISSUE THREAD

**Issue by andrei-dascalu** [smallnest/gen#45]
Hello,

I wanted to create structs from a mysql database for gorm (no other features) like this - from a db hosted on localhost:

```bash
gen --sqltype=mysql \
   	--connstr "$DB_USER:$DB_PASS@/$DB_NAME" \
   	--database $DB_NAME  \
   	--json \
    --out ./models \
   	--gorm \
   	--overwrite
```

what I am getting is this:

```
Error loading template model_base.go.tmpl not found
```

am I missing something?

If I copy the file from the `gen` repo into a local folder and pass the templateDir parameter, I do get results, but all accompanied by this error:

```
Error in loading model template, error: template: model:20: function "IsNullable" not defined
```

**Comment by smallnest** [comment]
try `templateDir ` option to set template dir to template dir (https://github.com/smallnest/gen/tree/master/template)

**Comment by alexj212** [comment]
@andrei-dascalu  Are you still having an issue with the latest. Can you share the output also please send output with the `--verbose` option
