### ISSUE TITLE
datetime2 support

### ISSUE THREAD

**Issue by viswanathanb** [smallnest/gen#53]
In MS SQL , I have some columns of data type `datetime2` which generates errors like `DATETIME2 error: unknown sql type: datetime2`. 

I suppose it can be fixed in the mapping.json or is there any option to use it ?

**Comment by smallnest** [comment]
![image](https://user-images.githubusercontent.com/865763/81487862-5b222180-9294-11ea-9141-00aaa3e18024.png)

**Comment by alexj212** [comment]
supported in v0.9 release coming shortly
