### ISSUE TITLE
numeric field in postgresql

### ISSUE THREAD

**Issue by andreTampan** [smallnest/gen#54]
Hi, I want to generate model from postgresql table below 

![image](https://user-images.githubusercontent.com/65219646/81659110-9aeb3380-9463-11ea-9eed-9a1de4320647.png)

however, when I generate it using gen, the numeric field somehow gone (not included when generate)

![image](https://user-images.githubusercontent.com/65219646/81660800-67110d80-9465-11ea-863d-8d1e3c58904c.png)

am I missing something?

Thanks

**Comment by smallnest** [comment]
It handled the `numeric` type: https://github.com/smallnest/gen/blob/master/template/mapping.json#L270

Have you installed latest gen? 

Or you check the customized data type: https://github.com/smallnest/gen#supported-data-types

**Comment by alexj212** [comment]
Tested in v0.9 release, with the ddl above with no issues. Release coming shortly
