### ISSUE TITLE
default dao 'getall' with 'paging' writes the sql and ALSO passes as parameters

### ISSUE THREAD

**Issue by jcolson** [smallnest/gen#64]
default dao 'getall' with 'paging' writes the sql and ALSO passes as parameters

this causes:
```sql: expected 0 arguments, got 2```
errors

```err = DB.SelectContext(ctx, &structs, sql, page, pagesize)```
should not pass page and pagesize, as the fmt.Sprintf is actually embedding the parameters in the actual query string

**Comment by jcolson** [comment]
`diff template-gen/dao_sqlx.go.tmpl dao_sqlx.go.tmpl 
53c53
< 	err = DB.SelectContext(ctx, &{{pluralize .StructName | toLower}}, sql, page, pagesize)
---
> 	err = DB.SelectContext(ctx, &{{pluralize .StructName | toLower}}, sql)`

**Comment by alexj212** [comment]
@jcolson thanks - will have an update shortly

**Comment by alexj212** [comment]
@jcolson  please check v 0.9.6 - SQLX code generation has been reworked along with documentation.

**Comment by jcolson** [comment]
fantastic - working like a champ!
