### ISSUE TITLE
表名称为goods,但是生成的结构体和go file文件都是good

### ISSUE THREAD

**Issue by zhaobu** [smallnest/gen#68]
如果mysql里面定义了一张表,最后一个字母是s,生成的golang文件会去掉s,生成的model结构体也会去掉s.

**Comment by smallnest** [comment]
We use to github.com/jinzhu/reflection to signular tables, to void using users,books as struct nsme.
Maybe we can add some special exlcuded words or use a smater lib

**Comment by alexj212** [comment]
I just pushed a change that will remove the pluralization, since table names can conflict. This affects urls, struct names etc.

**Comment by zhaobu** [comment]
I modified two parts of the source code to basically keep the generated Golang file consistent with the table name and the generated Model structure consistent with the table name.
part1: in main.go
![image](https://user-images.githubusercontent.com/8935615/84225071-ce77b700-ab10-11ea-9fda-933bb7bf46aa.png)

part2: in meta.go

![image](https://user-images.githubusercontent.com/8935615/84225282-5958b180-ab11-11ea-8053-86cf793606d4.png)

**Comment by zhaobu** [comment]
我测试了最新版,确实解决了这个问题,非常感谢.不过好像没有打tag.只能从master分支go get -u安装
