### ISSUE TITLE
How to iniitialize data null.String

### ISSUE THREAD

**Issue by bondhan** [smallnest/gen#7]
Hi,

I have struct with null.String data type (generated through smallnest/gen), however  I got the error 

> ./user_related_unit_test.go:92:82: cannot use "abc" (type string) as type null.String in field value

 when I tried to initialize it:

> 	UserCredentialObject := model.UserCredential{UserID: 1, Sequence: 1, AesPwdOld: "abc", AesPwdNew: null, PinBlockOld: "1234", PinBlockNew: "5678"}

**Comment by smallnest** [comment]
should define "abc" as `null.String`
