### ISSUE TITLE
[Bug report]sslmode issue caused by connstr in "regen" part of Makefile 

### ISSUE THREAD

**Issue by leopku** [smallnest/gen#76]
## `gen` version
```
0.9.7 (06/09/2020)
```

## OS
```
macOS 10.14.6
```

## Shell
```
zsh 5.3 (x86_64-apple-darwin18.0)
```

## Database
```
~ ❯❯❯ brew info postgresql
postgresql: stable 12.3 (bottled), HEAD
```

## Description

1. Run `gen --sqltype=postgres --connstr=...`, it works.

2. Run `make regen` with default `connstr` param, 

```
    --connstr=host=127.0.0.1 \
    port=5432 \
    user=myname \
    password=mypass \
    dbname=mydb \
    sslmode=disable \
```

it occurred with
```
Error pinging database: pq: SSL is not enabled on the server

Error in initializing db pq: SSL is not enabled on the server
make: *** [regen] Error 1
```

3. change `--connstr` in Makefile to below and run `make regen`, it should works well.
```
    --connstr="host=127.0.0.1 port=5432 user=myname password=mypass dbname=mydb sslmode=disable connect_timeout=10000" \
```
But `--connstr` in Makefile had been changed to default format like step 2.

## Maybe reason
I'm using zsh with [zprezto](https://github.com/sorin-ionescu/prezto).
Maybe it only broken in zsh? I don't know.

**Comment by alexj212** [comment]
I confirmed the bug - I believe I will have a fix shortly

**Comment by ttrasn** [comment]
This error still showing in v0.9.10 

OS: windows 10
psql (PostgreSQL) 12.3
