### ISSUE TITLE
Sqlite

### ISSUE THREAD

**Issue by mfdeux** [smallnest/gen#8]
I am having a hard time seeing how other databases than mysql are supported for inspection.  I cannot get sqlite database to work with the command line tool, and the code has mysql driver hardcoded.

**Comment by IsaacCruz** [comment]
> I am having a hard time seeing how other databases than mysql are supported for inspection. I cannot get sqlite database to work with the command line tool, and the code has mysql driver hardcoded.

Any comments about this?

**Comment by smallnest** [comment]
What is wrong with sqlite. 

Now gen uses https://github.com/jimsmart/schema to fetch schema so the below databases are supported:

- Microsoft SQL Server
- MySQL
- Oracle
- Postgres
- SQLite
