### ISSUE TITLE
希望能把数据库中对于字段的注释也能生成到 每一行的末尾

### ISSUE THREAD

**Issue by zhaobu** [smallnest/gen#85]
这是生成的格式
![image](https://user-images.githubusercontent.com/8935615/84419626-75f90480-ac4b-11ea-950f-0662cf6177be.png)
期望生成的格式类似这种看起来更紧凑,源码里不需要太多数据库相关的信息
![image](https://user-images.githubusercontent.com/8935615/84419848-c2444480-ac4b-11ea-8758-5153db215c11.png)
或者可以加一些参数来让用户选择,需要生成哪些,或者是修改model.go.tmpl模板文件就你自定义

**Comment by alexj212** [comment]
Please pull v0.9.10 - I pushed a release that fixes the issue
