### ISSUE TITLE
dao generated for --sqltype=mysql is using $1 binds instead of ?

### ISSUE THREAD

**Issue by jcolson** [smallnest/gen#88]
```gen --sqltype=mysql```

generates dao with:

```SELECT * FROM `account_members` WHERE member_id = $1```

I believe it should generate dao with:

```SELECT * FROM `account_members` WHERE member_id = ?```

**Comment by alexj212** [comment]
@jcolson  Yes it looks like 
MySQL uses the ? variant shown above
PostgreSQL uses an enumerated $1, $2, etc bindvar syntax
SQLite accepts both ? and $1 syntax
Oracle uses a :name syntax

I will call 
sqlx.DB.Rebind(string) string

to update the sql to be executed based on the db

**Comment by alexj212** [comment]
This is fixed in v0.9.11 - please retest

**Comment by jcolson** [comment]
that did the trick!  thanks
