### ISSUE TITLE
generate comments for each field

### ISSUE THREAD

**Issue by zhaobu** [smallnest/gen#94]
Whether to consider  generate comments for each field in the database after the field as well when generate model code

**Comment by alexj212** [comment]
@zhaobu Can you please provide some clearer information. I am not sure what you are asking for. We currently add comments to the model structs with a comment of the ddl from the table as  well as information about each column.

**Comment by zhaobu** [comment]
table create statements
![image](https://user-images.githubusercontent.com/8935615/85419822-197bda80-b5a5-11ea-9e85-b49f35ee16ae.png)

I mean use this table generate model code like this:
![image](https://user-images.githubusercontent.com/8935615/85420046-52b44a80-b5a5-11ea-9da3-18429f5f8ab9.png)

**Comment by alexj212** [comment]
@zhaobu Check out v0.9.14 - this has just been added along with some other features

**Comment by zhaobu** [comment]
ok,well done.
